version: "3.9"

services:
  frontend:
    image: mitochat-frontend:1.0.1
    container_name: mitochat_frontend
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - ./.streamlit/config.toml:/app/.streamlit/config.toml
    environment:
      - BACKEND_URL=http://backend:9000
