[server]
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = false
headless = true

# Optional: reduce info leakage
runOnSave = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false